  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
