name: GameDayGuessers - PR validation

on:
  pull_request:
    branches: ["main"]
  push:
    branches:
      - main

jobs:
  build-frontend:
    name: 'Validate frontend build'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build

  build-backend:
    name: 'Validate backend build'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: backend
        run: npm install

      - name: Build backend
        working-directory: backend
        run: npm run build

        
  auto-merge-dependabot:
    name: Auto merge Dependabot PR
    timeout-minutes: 10
    needs:
      - build-frontend
      - build-backend
    if: ${{ github.actor == 'dependabot[bot]' }}
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Merge PR from Dependabot
        uses: fastify/github-action-merge-dependabot@3.6.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor
          merge-method: rebase
